name: Build

on: [push]

jobs:
  mvc-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build MVC Login with Gradle
        run: ./gradlew :mvc-login:build
      - name: Unit Test MVC Login with Gradle
        run: ./gradlew :mvc-login:test
      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: mvc-login/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-mvc-login
          path: mvc-login/build/reports/jacoco/test/
  webflux-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build WebFlux Login with Gradle
        run: ./gradlew :webflux-login:build
      - name: Unit Test WebFlux Login with Gradle
        run: ./gradlew :webflux-login:test
      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: webflux-login/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-webflux-login
          path: webflux-login/build/reports/jacoco/test/